hmcts/pip-channel-management

- lombok.config
- src/main/java/uk/gov/hmcts/reform/demo/errorhandling/GlobalExceptionHandler.java
- src/test/java/uk/gov/hmcts/reform/rsecheck/errorhandling/ExceptionResponseTest.java
- src/test/java/uk/gov/hmcts/reform/rsecheck/errorhandling/GlobalExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/rsecheck/errorhandling/exceptions/ChannelNotFoundExceptionTest.java
https://tools.hmcts.net/jira/browse/PUB-503
Added Global Exception Handling Tests
```
[ ] Yes
[x] No
```
> PUB-503 - Global Exception Handling Tests

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementController.java
https://tools.hmcts.net/jira/browse/PUB-1356
Added authentication to channel management endpoint + update test profile
```
[ ] Yes
[x] No
```
> PUB-1356 - Fix auth flow

- charts/pip-channel-management/values.yaml
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/Application.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementController.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/errorhandling/GlobalExceptionHandler.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/external/subscriptionmanagement/Channel.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/external/subscriptionmanagement/SearchType.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/external/subscriptionmanagement/Subscription.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/SubscriberListService.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/utils/ThirdPartyApi.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/SubscriberListServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/utils/ThirdPartyServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-949
added  api values for third party, changed channel model to hold the correct API_COURTEL value
```
[ ] Yes
[x] No
```
> PUB-949 added third party api value builder to add to subscriptions

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/Application.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementController.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/errorhandling/GlobalExceptionHandler.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/external/subscriptionmanagement/Channel.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/external/subscriptionmanagement/SearchType.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/external/subscriptionmanagement/Subscription.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/SubscriberListService.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/utils/ThirdPartyApi.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/SubscriberListServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/utils/ThirdPartyServiceTest.java
N/A
Merging integration into master
```
[ ] Yes
[x] No
```
> Merge integration into master

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementController.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/errorhandling/GlobalExceptionHandler.java
https://tools.hmcts.net/jira/browse/PUB-1341
Updating logging for Channel Management
```
[ ] Yes
[x] No
```
> PUB-1341 - Updated logging

- charts/pip-channel-management/Chart.yaml
- charts/pip-channel-management/values.yaml
https://tools.hmcts.net/jira/browse/PUB-1405
Added in Courtel API
```
[ ] Yes
[x] No
```
> PUB-1405 - Added in courtel API

- charts/pip-channel-management/Chart.yaml
N/A
Updated chart version
```
[ ] Yes
[x] No
```
> Update chart version

- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/SubscriberListService.java
https://tools.hmcts.net/jira/browse/PUB-1522
Removed a log that was outputting a map containing the users email.
```
[ ] Yes
[x] No
```
> PUB-1522 Removed log with user email

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/PUB-1476
Updated the name in application.yaml which is used by app insights.
```
[ ] Yes
[x] No
```
> PUB-1476 Updated app insights name

- src/main/resources/templates/languages/cy/familyDailyCauseList.json
- src/main/resources/templates/languages/en/familyDailyCauseList.json
https://tools.hmcts.net/jira/browse/PUB-1710
Added extra header to ensure Family PDF links up.
```
[ ] Yes
[ ] No
```
> PUB-1710 - Updated headers

- .github/workflows/ci.yml
- Dockerfile
- build.gradle
- config/checkstyle/checkstyle.xml
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/config/AzureBlobFunctionalTestConfiguration.java
- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/config/AzureBlobTestConfiguration.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/AccountManagementService.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CivilDailyCauseListSummaryConverter.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/converters/SjpPressListFileConverter.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/DataManipulation.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/GeneralHelper.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/PartyRoleHelper.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/listmanipulation/EtDailyListManipulation.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/listmanipulation/MagistratesStandardListHelper.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/config/AzureBlobTestConfiguration.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/config/WebClientTestConfiguration.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/AccountManagementServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/DataManagementServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/converters/SjpPressListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/converters/SscsDailyListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/DataManipulationTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/GeneralHelperTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/PartyRoleMapperTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/listmanipulation/CrownWarnedListManipulationTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/utils/ThirdPartyServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1678
Upgraded channel management from Java 11 to 17.
```
[ ] Yes
[x] No
```
> PUB-1678 Java 17 upgrade

- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/EtFortnightlyPressListSummaryConverter.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/listmanipulation/EtFortnightlyPressListHelper.java
- src/main/resources/templates/etFortnightlyPressList.html
- src/main/resources/templates/languages/cy/etFortnightlyPressList.json
- src/main/resources/templates/languages/en/etFortnightlyPressList.json
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/converters/EtFortnightlyPressListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/listmanipulation/EtFortnightlyPressListHelperTest.java
https://tools.hmcts.net/jira/browse/PUB-1705
Cleaned up the ET Fortnightly PDF with the following:
1) Remove Service header
2) Ensure main header is wrapped
3) Updated Last Updated to Last updated
4) Updated times to use standard method
```
[ ] Yes
[x] No
```
> PUB-1705 - ET Fortnightly Clean Up

- Jenkinsfile_CNP
- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
https://tools.hmcts.net/jira/browse/PUB-1772
Add functional test for publication management service. INTERNAL_ERROR_CODE functional tests are missing because error will only occurred when there is an invalid json which is not possible. We cannot upload invalid json to the system.
[ ] Yes
[x] No
> PUB-1772 Add functional test for Publication Management Service

- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/GeneralHelper.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/GeneralHelperTest.java
https://tools.hmcts.net/jira/browse/PUB-1801
Pdf and email summary generation is failed when OrganizationDetails attribute is missing from schema.
[ ] Yes
[x] No
> PUB-1801 Crown Daily List Pdf Generation bug fix

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/external/datamanagement/ListType.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/LanguageResourceHelper.java
- src/main/resources/templates/languages/cy/sscsDailyList.json
- src/main/resources/templates/languages/cy/sscsDailyListAdditionalHearings.json
- src/main/resources/templates/languages/en/sscsDailyList.json
- src/main/resources/templates/languages/en/sscsDailyListAdditionalHearings.json
- src/main/resources/templates/sscsDailyList.html
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SscsDailyListArtefactSummaryConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/converters/SscsDailyListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/LanguageResourceHelperTest.java
https://tools.hmcts.net/jira/browse/PUB-1768
Add SSCS daily list - additional hearings
```
[ ] Yes
[x] No
```
> PUB-1768 Add SSCS daily list - additional hearings

- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PUB-1811
Removed unneeded variables
```
[ ] Yes
[x] No
```
> PUB-1811 - Removed unneeded variables

- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SscsDailyListSummaryConverter.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/converters/SscsDailyListFileConverter.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/DataManipulation.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SscsDailyListArtefactSummaryConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/converters/SscsDailyListFileConverterTest.java
https://tools.hmcts.net/jira/browse/PUB-1823
Correct legal advisor Welsh name for SSCS daily list
```
[ ] Yes
[x] No
```
> PUB-1823 Correct legal advisor Welsh name for SSCS daily list

- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/external/datamanagement/ListType.java
Remove lombok @nonNull annotation which confuses Sonar
```
[ ] Yes
[x] No
```
> Remove lombok @NonNull annotation which confuses Sonar

- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
N/A
Fixed channel management tests
```
[ ] Yes
[x] No
```
> Updated artefacts

- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
N/A
Updated SJP Public List
```
[ ] Yes
[x] No
```
> Update sjp public list

- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/LocationHelper.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/EtDailyListSummaryConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/EtFortnightlyPressListSummaryConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/converters/EtDailyListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/listmanipulation/EtFortnightlyPressListHelperTest.java
- src/test/resources/mocks/etDailyList.json
- src/test/resources/mocks/etFortnightlyPressList.json
https://tools.hmcts.net/jira/browse/PUB-1902
Cleanup ET Lists validation schema files and mock data files.
[ ] Yes
[x] No
> PUB-1902 Cleanup ET Lists validation schema

- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
Replace missing artefacts for functional tests
```
[ ] Yes
[x] No
```
> Replace missing artefacts for functional tests

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-1910
Update dependencies + suppressions
```
[ ] Yes
[x] No
```
> PUB-1910 - Update Dependencies + suppressions

- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/converters/EtDailyListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/converters/EtFortnightlyPressListFileConverterTest.java
- src/test/resources/mocks/etDailyList.json
- src/test/resources/mocks/etFortnightlyPressList.json
https://tools.hmcts.net/jira/browse/PUB-1925
Updated test files for ET lists
```
[ ] Yes
[x] No
```
> PUB-1925 - Updated files for ET Lists

- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
https://tools.hmcts.net/jira/browse/PUB-1924
Fix tests with blob deletion in staging
```
[ ] Yes
[x] No
```
> PUB-1924 Fix tests with blob deletion in staging

- src/main/java/uk/gov/hmcts/reform/pip/channel/management/config/WebClientConfig.java
https://tools.hmcts.net/jira/browse/PUB-1958
Up the max size for service-to-service data transfer to 2MB from the default 256K
```
[ ] Yes
[x] No
```
> PUB-1958 Up the max size for service-to-service data transfer to 2MB from 256K

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-1991
Updated to retrigger build
```
[ ] Yes
[x] No
```
> PUB-1991 - Update

- src/main/java/uk/gov/hmcts/reform/pip/channel/management/errorhandling/GlobalExceptionHandler.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/AccountManagementService.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/SubscriberListService.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/AccountManagementServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-1732
Update logging
```
[ ] Yes
[x] No
```
> PUB-1732 Update logging

- config/owasp/suppressions.xml
Suppress CVE-2023-34411
https://nvd.nist.gov/vuln/detail/CVE-2023-34411
```
[ ] Yes
[x] No
```
> Suppress CVE-2023-34411

- src/main/java/uk/gov/hmcts/reform/pip/channel/management/config/WebConfiguration.java
Ignore trailing slash in spring boot v3 endpoints
```
[ ] Yes
[x] No
```
> Ignore trailing slash in spring boot v3 endpoints

- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SjpPressListSummaryConverter.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/SjpPressListFileConverter.java
- src/main/resources/templates/sjpPressList.html
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SjpPressListSummaryConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/SjpPressListFileConverterTest.java
- src/test/resources/mocks/sjpPressList.json
- src/test/resources/mocks/sjpPressMockJul22.json
https://tools.hmcts.net/jira/browse/PUB-1985
Allow organisation details for accused party
```
[ ] Yes
[x] No
```
> PUB-1985 Allow organisation details for accused party

- build.gradle
- config/owasp/suppressions.xml
N/A
Fixed pipeline vulnerability
```
[ ] Yes
[x] No
```
> Fixed vulnerability

- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/IacDailyListFileConverter.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/JudiciaryHelper.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/CopListHelper.java
- src/main/resources/templates/copDailyCauseList.html
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CopDailyCauseListSummaryConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/CopCauseListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/JudiciaryHelperTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/CopListHelperTest.java
- src/test/resources/mocks/copDailyCauseList.json
- src/test/resources/mocks/copDailyCauseListMissingRegion.json
- src/test/resources/mocks/copDailyCauseListMissingRegionalJoh.json
- src/test/resources/mocks/judiciaryManipulation.json
https://tools.hmcts.net/jira/browse/PUB-2106
COP_DAILY_CAUSE_LIST PDF update:
- Added courtRoomName to accordion heading
- Displayed johKnownAs and use isPresiding for judiciary in accordion
```
[ ] Yes
[x] No
```
> PUB-2106 COP_DAILY_CAUSE_LIST PDF update

- build.gradle
N/A
Fixed Spring CVE
```
[ ] Yes
[x] No
```
> Fixed spring suppression

- charts/pip-channel-management/Chart.yaml
- charts/pip-channel-management/values.dev.template.yaml
- charts/pip-channel-management/values.stg.template.yaml
- charts/pip-channel-management/values.yaml
https://tools.hmcts.net/jira/browse/PUB-2192
Update to Workload identity
```
[ ] Yes
[x] No
```
> PUB-2192 - Chart update workload identity

- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CrownDailyListSummaryConverter.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/CrimeListHelper.java
- src/main/resources/templates/crownDailyList.html
- src/main/resources/templates/languages/cy/crownDailyList.json
- src/main/resources/templates/languages/en/crownDailyList.json
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CrownDailyListSummaryConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/CrownDailyListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/CrownDailyListHelperTest.java
- src/test/resources/mocks/crownDailyList.json
https://tools.hmcts.net/jira/browse/PUB-2017
Add reporting restriction detail to crown daily list
```
[ ] Yes
[x] No
```
> PUB-2017 - Added reporting restrictions to Crown daily list

- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/FamilyMixedListHelper.java
- src/main/resources/templates/civilAndFamilyDailyCauseList.html
- src/main/resources/templates/civilDailyCauseList.html
- src/main/resources/templates/familyDailyCauseList.html
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/CivilAndFamilyCauseListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/FamilyCauseListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/FamilyMixedListHelperTest.java
- src/test/resources/mocks/familyDailyCauseList.json
https://tools.hmcts.net/jira/browse/PUB-2230
Changes made to PDF generation so party information is not displayed if more than one cases in a hearing.
```
[ ] Yes
[x] No
```
> PUB-2230 Handle parties for hearing with multiple cases

- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/MagistratesStandardListSummaryConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/MagistratesStandardListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/MagistratesStandardListHelperTest.java
- src/test/resources/mocks/magistratesStandardList.json
https://tools.hmcts.net/jira/browse/PUB-2090
Update functional test staging data with double square brackets
```
[ ] Yes
[x] No
```
> PUB-2090 Update functional test staging data with double square brackets

- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SjpPressListSummaryConverter.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SjpPressListSummaryConverterTest.java
- src/test/resources/mocks/sjpPressList.json
https://tools.hmcts.net/jira/browse/PUB-2125
Add case URN to SJP Press list email summary
```
[ ] Yes
[x] No
```
> PUB-2125 Add case URN to SJP Press list email summary

- README.md
- charts/pip-channel-management/Chart.yaml
- charts/pip-channel-management/values.yaml
https://tools.hmcts.net/jira/browse/PUB-2245
Updated README and removed unused value from chart
```
[ ] Yes
[x] No
```
> PUB-2245 - Updated README

- .github/workflows/terraform_format.yml
- infrastructure/state.tf
https://tools.hmcts.net/jira/browse/PUB-2182
Add terraform_format.yml
```
[ ] Yes
[X] No
```
> PUB-2182 add terraform_format.yml

- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
https://tools.hmcts.net/jira/browse/PUB-2208
Add OPA results functional tests
```
[ ] Yes
[x] No
```
> PUB-2208 Add OPA results functional tests

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/PUB-2337
Enable graceful shutdown
```
[ ] Yes
[x] No
```
> PUB-2337 - Added graceful shutdown

- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/IacDailyListFileConverterTest.java
- src/test/resources/mocks/iacDailyList.json
https://tools.hmcts.net/jira/browse/PUB-2262
Removing Individual Middle Name attribute from iac Daily List
```
[ ] Yes
[x] No
```
> PUB-2262: Removing Individual Middle Name attribute from iacDailyList

- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SscsDailyListSummaryConverter.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/SscsListHelper.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SscsDailyListArtefactSummaryConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/SscsDailyListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/SscsListHelperTest.java
- src/test/resources/mocks/sscsDailyList.json
https://tools.hmcts.net/jira/browse/PUB-2339
Updated SSCS to read from Respondent
```
[ ] Yes
[x] No
```
> Pub 2339 sscs party role respondent

- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/IacDailyListSummaryConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/IacDailyListFileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/SittingHelperTest.java
- src/test/resources/mocks/iacDailyList.json
https://tools.hmcts.net/jira/browse/PUB-2264
Adding Session Channel to IAC Daily list and updating tests
```
[ ] Yes
[x] No
```
> Pub 2264: Adding Session Channel to IAC Daily list and updating tests

- README.md
- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2121
Update pip-data-models version
```
[ ] Yes
[x] No
```
> PUB-2121 Update pip-data-models version

- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementTest.java
Replace user ID in functional test
```
[ ] Yes
[x] No
```
> Replace user ID in functional test

- src/main/resources/templates/crownFirmList.html
https://tools.hmcts.net/jira/browse/PUB-2319
Fixed Crown Firm List table border formatting issue
```
[ ] Yes
[x] No
```
> PUB-2319 Fixed Crown Firm List table border formatting issue

- src/test/resources/mocks/etDailyList.json
- src/test/resources/mocks/etFortnightlyPressList.json
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/PUB-2263
```
[ ] Yes
[X] No
```
> PUB-2263 - Individual Middle Name removed from the ET Lists

- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementController.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/database/AzureBlobService.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/PublicationFileSizes.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementControllerTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/database/AzureBlobServiceTest.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementServiceTest.java
https://tools.hmcts.net/jira/browse/PUB-2122
Add endpoints to get blob size and check file existence
```
[ ] Yes
[x] No
```
> PUB-2122 Add endpoints to get blob size and check file existence

- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/SjpPressListFileConverter.java
- src/main/resources/templates/sjpPressList.html
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/SjpPressListFileConverterTest.java
- src/test/resources/mocks/sjpPressList.json
https://tools.hmcts.net/jira/browse/PUB-2428
SJP Press List - make DOB and age fields optional
```
[ ] Yes
[x] No
```
> PUB-2428 SJP Press List DOB and age optional

- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/SjpPressListFileConverter.java
- src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/SjpPressListFileConverterTest.java
- src/test/resources/mocks/sjpPressList.json
https://tools.hmcts.net/jira/browse/PUB-2459
Handle SJP Press List without offence wording
```
[ ] Yes
[x] No
```
> PUB-2459 Handle SJP Press List without offence wording

- src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
- src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/OpaResultsHelper.java
- src/test/resources/mocks/opaResults.json
https://tools.hmcts.net/jira/browse/PUB-2474
OPA Results - Move offence to individualDetails/organisationDetails level
```
[ ] Yes
[x] No
```
> PUB-2474 OPA Results - Move offence to individualDetails/organisationDetails level
